############################################ Parameters for downloading the dataset ############################################
# Threshold values for the logcat filter 
runtime_per_file: 15                                  # Runtime measured by the logcat files
num_logcat_lines_per_file: 50                         # Number of logcat events in the logcat file 
freq_logcat_event_per_file: 2                         # Average frequency of the logcat events i.e. number of logcat events per second

# Dataset type (Can take one of the following values: {'std-dataset', 'bench-dataset', 'cdyear1-dataset', 'cdyear2-dataset', 'cdyear3-dataset'})
dataset_type: 'cd-dataset'

dataset_download_flag: False                          # Flag that decides whether or not to download the dataset from Dropbox
################################################################################################################################

######################################### Parameters for performing late-stage fusion ##########################################
dataset_base_location: "/data/hkumar64/projects/arm-telemetry/xmd/data"            # Base location where all the datasets will be stored
results_base_location: "/data/hkumar64/projects/arm-telemetry/xmd/results"         # Base location where all the result files will be stored
create_runs_dir: False                                                             # If True, then will create a runs dir to track the experimental run
seed: 10                                                                           # Random seed to be used for this experiment
device: "cuda:1"
################################################################################################################################

################################## Parameters for feature engineering (passed to collate_fn) ###################################
collected_duration: 90                                # Duration for which the telemetry logs is collected
# Parameters for feature reduction (for GLOBL file_type)
chunk_time: 1                                         # Window size (in s) over which the spectrogram will be calculated
feature_engineering_flag: True                        # Flag that decides whether to perform feature engineering on the raw time series data
reduced_frequency_size: 12                            # Number of principal components to consider for dimensionality reduction of the frequency axis
reduced_time_size: 4                                  # Number of principal components to consider for dimensionality reduction of the time axis
n_fft: 1024                                           # Order of fft for stft [Used in dimensionality reduction]

# Parameters for resampling GLOBL
custom_num_datapoints: 150000                         # Number of data points in the resampled time series
resampling_type: "custom"                             # Type of resampling. Can take one of the following values: ['max', 'min', 'custom']
resample: True                                        # Flag to determine whether or not to resample

# Parameters for feature engineering of HPC
histogram_bins: 32                                    # Number of bins into which the HPC time series telemetry is divided
################################################################################################################################

########################################## Parameters for configuring the dataloader ###########################################
num_workers: 10                                       # Number of workers for the dataloader
train_batchsz: 20                                     # Batch size for training
test_batchsz: 5                                       # Batch size for testing

# Parameters for selecting subset of samples from the dataset [used during testing]
num_train: 50                                         # Number of training samples to consider
num_test:  5                                          # Number of testing samples to consider

# Flags for shuffling the train, and test dataset
train_shuffle: True                                   # Flag for shuffling the training data
test_shuffle: False                                   # Flag for shuffling the testing data
################################################################################################################################
